/***********************************************************************
 *  LAG - Source file header
 *
 *              Layer:
 *             Module:
 *           $Logfile:   $
 *         Originator:  Adam Hawley
 *          $Revision:   $
 *       on     $Date:   $
 *       by   $Author:   $
 *
 *           Synopsis:  General stuff
 *
 *              Notes:  None.
 *
 ************************************************************************
 *
 *  (C) Copyright 1996, Logica UK Ltd. All rights reserved.
 *
 ************************************************************************
 */

#ifndef LGGLOBLS_H
#define LGGLOBLS_H

#include "LGlagapp.h"

// This stuff in global header file

extern LAGApplication oTheApplication;

#endif // LGGLOBLS_H
