/***********************************************************************
 *  LAG - Source file header
 *
 *              Layer:  
 *             Module:  
 *           $Logfile:   $
 *         Originator:  Adam Hawley
 *          $Revision:   $
 *       on     $Date:   $
 *       by   $Author:   $
 *
 *           Synopsis:  class definition for 
 *
 *              Notes:  None.
 *
 ************************************************************************
 *
 *  (C) Copyright 1996, Logica UK Ltd. All rights reserved.
 *
 ************************************************************************
 */
#ifndef LGTEMPLATE_H
#define LGTEMPLATE_H

/************************************************************************
 *
 *   CLASS DECLARATION
 *
 *               Name:  
 *
 *           Synopsis:  .
 *
 *              Notes:  .
 *
 ************************************************************************
 */

class ClassName <: pub/prot/priv ParentClass>
{

// Attributes

public:

protected:

private:

// Methods

public:
	// Constructors
	ClassName();

	// Destructors
	~ClassName();

protected:

private:

};

#endif // LGTEMPLATE_H
